spring.application.name=online-verification-system

server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://nity209222:nitesh1234@cluster0.tyu2pm0.mongodb.net/online_verification?retryWrites=true&w=majority&appName=Cluster0

# JWT
jwt.secret=MyVerySecureOnlineVerificationSystemSecretKey123456789
jwt.expiration=86400000

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Logging
logging.level.com.verification.system=INFO