export const API_BASE_URL =
  import.meta.env.VITE_API_URL || "http://localhost:5000/api";

export const ROLES = {
  APPLICANT: "applicant",
  INSPECTOR: "inspector",
  ADMIN: "admin",
};

export const APPLICATION_STATUS = {
  SUBMITTED: "SUBMITTED",
  DOCUMENT_VERIFICATION: "DOCUMENT_VERIFICATION",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  SCHEDULED: "SCHEDULED",
  INSPECTION: "INSPECTION",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
};